version: '3.8'

services:
 nginx:
   image: nginx:latest
   ports:
     - "89:80"
   volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
     - ./src:/var/www/html:ro
   depends_on:
     - php

 php:
   build: ./php
   volumes:
     - ./src:/var/www/html:rw
